### ISSUE TITLE
Initial state of entities are not working properly

### ISSUE THREAD

**Issue by paulozavaleta** [ringo-framework/formbar#10]
The entities in a "create_snippet" formulary are not properly instanced. When an entity is created in the source section and given a default value, said value is not taken in count when the entity is instanced. 

`<entity id="type" name="type" label="Type" type="integer" value="1">`

For instance, when an entity is evaluated in a conditional statement, the application breaks and states that the entity has no value assigned to it even when a default value was given to it in the source section.

`<if expr=" type == 1">`

The error message shown is:

OperandMissmatchError: Can not use operands '(None, <type 'NoneType'>, 1, <type 'int'>)' on operator '=='. Type of operands must be equal

**Comment by toirl** [comment]
Fixed with 9b6ce2f9f6ba2a336ce25adcb5d443c75274de59
